name: OVMF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 0-6'

    
jobs:

  download_ci_ovmf_and_deploy:
    name: Download CI OVMF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}