name: OVMF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 0-6'

    
jobs:
  download_ovmf_and_create_artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download OVMF
      run: cargo run
    - name: Upload artifact  
      uses: actions/upload-artifact@v2
      with:
        name: OVMF
        path: |
         ./ci-aarch64-debug
         ./ci-aarch64-release
         ./ci-x64-debug
         ./ci-x64-release
    
      
  
    